on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sam-app/hello-world
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
          cache-dependency-path: ./sam-app/hello-world/package-lock.json
      - run: npm ci
      - run: npm test
      
  deploy:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./sam-app
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '22.x'
      #     registry-url: https://registry.npmjs.org/
      #     cache: 'npm'
      #     cache-dependency-path: ./sam-app/hello-world/package-lock.json
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: sam build
      - run: sam deploy